import "./globals.css";
import Navbar from "./ui/navbar";
import { kameron } from "./ui/fonts";

export const metadata = {
  title: "Artistique",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="mytheme" className="bg-neutral">
      <body className={`${kameron.className} antialiased `}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
